image: container-registry.ovh.rtgi.eu:5000/gitlab-ci-lkf-ubuntu
variables:
  registry: container-registry.ovh.rtgi.eu

before_script:
- docker info

build:
  stage: build
  only:
    refs:
      - linkfluence
  script:
  - lein with-profile repo do clean, deploy releases
